[Desktop Entry]
Name=Adwaita-X-dark-custom
Type=X-GNOME-Metatheme
Comment=

[X-GNOME-Metatheme]
GtkTheme=Adwaita-X-dark
MetacityTheme=Adwaita-X-dark
IconTheme=Mint-X-Aqua
GtkColorScheme=base_color:#ffffff,bg_color:#ededed,tooltip_bg_color:#343434,selected_bg_color:#4a90d9,text_color:#2e3436,fg_color:#2e3436,tooltip_fg_color:#ffffff,selected_fg_color:#fff
CursorTheme=DMZ-White
CursorSize=24
NotificationTheme=standard
