#!/bin/bash
wired_interfaces="en.*|eth.*"
if [[ "$1" =~ $wired_interfaces ]]; then
    case "$2" in
        pre-up|up)
            nmcli radio wifi off
            ;;
        pre-down|down)
            nmcli radio wifi on
            ;;
    esac
fi
